### ISSUE TITLE
Feature request: support for building out of source

### ISSUE THREAD

**Issue by egarrulo** [alamaison/emacs-cmake-project#7]
I am new to CMake, so evaluate this request accordingly.

A recommended practice when using CMake is to build out of the source directory.  This is already performed by `cmake-project-configure-project` by manually adding a subdirectory to its default input.  Maybe, CMake Project could have a custom variable to automatically add this subdirectory to its default input?

Thanks for your attention.

**Comment by egarrulo** [comment]
See also this answer to a related question on StackOverflow: http://stackoverflow.com/a/11144109/370132

**Comment by miabrahams** [comment]
The default behavior is to use or create a separate build directory `bin` inside the project root directory.

**Comment by alamaison** [comment]
As @miabrahams says, the [default](https://github.com/alamaison/emacs-cmake-project/blob/master/cmake-project.el#L88) is to use a build directory called `bin`.  If this is not what is happening, maybe you changed it to something different.
